Partie 1 – Explorer les données
1) Charger les données CSV ;

In [3]:
import pandas as pd

df = pd.read_csv("../data/smart_building_raw.csv")

2) Afficher les premières lignes du dataset ;

In [4]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

3) Afficher les dernières lignes du dataset ;

In [5]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

4) Combien d'observations contient le dataset ?

In [ ]:
print("Nombre d'observations :", df.shape[0])

Nombre d'observations : 507
Nombre de variables : 14

In [ ]:
5) Combien de variables possède le dataset ?

In [9]:
print("Nombre de variables :", df.shape[1])

Nombre de variables : 14

6) Identifier les variables numériques ;

In [13]:
print(df.select_dtypes(include="number").columns.tolist())

['id_mesure', 'temperature', 'humidite', 'co2', 'occupation', 'consommation_kwh']

7) Identifier les variables catégorielles ;

In [15]:
df.select_dtypes(include="object").columns.tolist()

['date',
 'batiment',
 'type_batiment',
 'zone',
 'mode_climatisation',
 'etat_systeme',
 'jour_semaine',
 'alerte']

8) Identifier les dates

In [18]:
print(df.dtypes)

id_mesure               int64
date                   object
batiment               object
type_batiment          object
zone                   object
temperature           float64
humidite              float64
co2                   float64
occupation            float64
consommation_kwh      float64
mode_climatisation     object
etat_systeme           object
jour_semaine           object
alerte                 object
dtype: object

In [25]:
print(df.date)

0     2025-02-13 06:00:00
1     2025-03-10 12:00:00
2     2025-05-04 00:00:00
3     2025-01-19 00:00:00
4     2025-04-24 06:00:00
              ...
502   2025-01-27 12:00:00
503   2025-03-09 12:00:00
504   2025-03-29 00:00:00
505   2025-04-19 18:00:00
506   2025-01-26 12:00:00
Name: date, Length: 507, dtype: datetime64[ns]

9) Identifier les identifiants

In [28]:
colonnes_id = [col for col in df.columns if "id" in col.lower()]

print("Colonnes pouvant être des identifiants :", colonnes_id)

Colonnes pouvant être des identifiants : ['id_mesure', 'humidite']

0      1174
1      1275
2      1493
3      1073
4      1454
       ...
502    1107
503    1271
504    1349
505    1436
506    1103
Name: id_mesure, Length: 507, dtype: int64

10) Déterminer les statistiques : moyenne, médiane, minimum, maximum, écart-type et quartiles.

In [31]:
df.describe()

,id_mesure,date,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,502,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,2025-03-04 13:26:03.346613504,24.154141,57.864113,844.150000,44.850299,169.069323
min,1001.000000,2025-01-01 00:00:00,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,2025-02-01 01:30:00,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,2025-03-04 21:00:00,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,2025-04-04 22:30:00,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,2025-05-05 18:00:00,96.000000,160.000000,6000.000000,116.000000,336.200000
std,144.782769,NaN,7.418465,16.026336,582.181386,24.949139,53.164294

11) Y a-t-il des variables potentiellement problématiques ?

In [32]:
print("valeurs manquantes : ")
df.isnull().sum()

valeurs manquantes :

id_mesure              0
date                   5
batiment               0
type_batiment          4
zone                   0
temperature           12
humidite              11
co2                    7
occupation             6
consommation_kwh       5
mode_climatisation     5
etat_systeme           0
jour_semaine           5
alerte                 0
dtype: int64

In [40]:
print("Nombre de doublons :", df.duplicated().sum())

Nombre de doublons : 7

In [ ]:
#Variables avec très peu de valeurs différentes

for colonne in df.columns:
    print(colonne, ":", df[colonne].nunique(), "valeurs uniques")

id_mesure : 500 valeurs uniques
date : 495 valeurs uniques
batiment : 8 valeurs uniques
type_batiment : 16 valeurs uniques
zone : 4 valeurs uniques
temperature : 144 valeurs uniques
humidite : 305 valeurs uniques
co2 : 392 valeurs uniques
occupation : 108 valeurs uniques
consommation_kwh : 445 valeurs uniques
mode_climatisation : 7 valeurs uniques
etat_systeme : 3 valeurs uniques
jour_semaine : 7 valeurs uniques
alerte : 2 valeurs uniques

In [42]:
#variables categorielle

print("variables categorielles : ", df.select_dtypes(include="object"))

variables categorielles :      batiment      type_batiment zone mode_climatisation etat_systeme  \
0         B8           Entrepôt    A                Eco       Normal
1         B7             Bureau    D                Eco       Normal
2         B5  Centre commercial    B             Normal       Normal
3         B6         Université    D             Normal       Normal
4         B7             Bureau    D             Normal       Normal
..       ...                ...  ...                ...          ...
502       B2              École    C             Normal       Normal
503       B3            Hôpital    B                Eco       Alerte
504       B5  Centre commercial    B                Eco       Normal
505       B7             Bureau    C              Boost       Normal
506       B2              École    D             Normal        Panne

    jour_semaine alerte
0          Jeudi    Non
1          Lundi    Non
2       Dimanche    Oui
3       Dimanche    Non
4          Jeudi    Non
..           ...    ...
502        Lundi    Non
503     Dimanche    Oui
504       Samedi    Non
505       Samedi    Oui
506     Dimanche    Non

[507 rows x 7 columns]

12) Pour les données incohérentes :

a) rechercher des valeurs telles que humidité < 0 ;

In [44]:
df[df["humidite"] < 0]

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
281,1126,2025-02-01 06:00:00,B2,École,D,24.8,-5.0,759.0,57.0,225.2,Boost,Normal,Samedi,Non
335,1036,2025-01-09 18:00:00,B4,Bureau,D,21.2,-8.0,160.0,25.0,120.2,Normal,Alerte,Jeudi,Non
366,1216,2025-02-23 18:00:00,B3,Hôpital,B,23.2,-12.0,702.0,41.0,119.8,Normal,Normal,Dimanche,Non

b) rechercher des valeurs telles que humidité > 100 ;

In [45]:
df[df["humidite"] > 100]

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
59,1246,2025-03-03 06:00:00,B5,Centre commercial,A,24.2,108.0,813.0,18.0,-15.0,Normal,Normal,Lundi,Non
103,1016,2025-01-04 18:00:00,B6,Université,B,26.9,145.0,670.0,28.0,175.9,Normal,Normal,Samedi,Non
128,1156,2025-02-08 18:00:00,B1,Bureau,A,NaN,160.0,941.0,37.0,149.8,Eco,Normal,Samedi,Oui
160,1186,2025-02-16 06:00:00,B8,Entrepôt,B,24.9,125.0,NaN,18.0,123.5,Normal,Normal,Dimanche,Non
268,1276,2025-03-10 18:00:00,B1,Bureau,D,26.0,140.0,633.0,25.0,148.3,Normal,Normal,Lundi,Non
327,1066,2025-01-17 06:00:00,B2,École,C,25.8,132.0,646.0,14.0,93.6,Eco,Normal,Vendredi,Non
342,1096,2025-01-24 18:00:00,B8,Entrepôt,A,20.3,110.0,783.0,55.0,121.0,Normal,Normal,Vendredi,Non

c) rechercher des valeurs telles que température extrêmement élevée ;

In [46]:
print(df["temperature"].describe())

count    495.000000
mean      24.154141
std        7.418465
min      -30.000000
25%       21.600000
50%       24.000000
75%       26.000000
max       96.000000
Name: temperature, dtype: float64

In [49]:
df.nlargest(10, "temperature") #afficher les 10 plus grandes valeurs de la colonne temperature

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
116,1181,2025-02-15 00:00:00,B6,Université,A,96.0,86.5,874.0,115.0,241.5,Normal,Normal,Samedi,Non
499,1021,2025-01-06 00:00:00,B2,École,A,95.2,65.0,314.0,43.0,246.3,Normal,Normal,Lundi,Non
161,1061,2025-01-16 00:00:00,B5,Centre commercial,D,88.0,50.5,393.0,62.0,196.6,Normal,Alerte,Jeudi,Non
7,1141,2025-02-05 00:00:00,B2,École,D,72.5,78.3,257.0,100.0,239.7,Boost,Alerte,Mercredi,Non
157,1361,2025-04-01 00:00:00,B3,Hôpital,D,34.2,60.9,828.0,41.0,270.3,Normal,Normal,Mardi,Non
199,1146,2025-02-06 06:00:00,B7,Bureu,C,32.2,53.8,621.0,103.0,-20.0,Normal,Normal,Jeudi,Non
419,1191,2025-02-17 12:00:00,B2,École,D,31.6,NaN,1057.0,57.0,255.3,BOOST,Normal,Lundi,Oui
48,1472,2025-04-28 18:00:00,B3,Hôpital,C,31.2,58.1,531.0,30.0,224.2,Boost,Normal,Lundi,Non
370,1268,2025-03-08 18:00:00,B1,Bureau,B,30.6,60.6,684.0,0.0,179.4,Normal,Normal,Samedi,Non
393,1157,2025-02-09 00:00:00,B8,Entrepôt,B,30.6,33.0,241.0,113.0,319.5,Boost,Normal,Dimanche,Non